spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?userSSL=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
#config-location: classpath:mybatis-config.xml
#type-aliases-package: com.fan.model
#mapper-locations: classpath*:static/mapper/*.xml