server:
  port: 8090
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?userSSL=false&characterEncoding=utf-8&serverTimezone=UTC
        #jdbc:mysql://localhost:3306/test?userSSL=false&characterEncoding=utf-8&serverTimezone=UTC
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.fan.domain